# Generated by Django 5.1.5 on 2025-01-25 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='description',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
