# Generated by Django 5.1.5 on 2025-01-28 04:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0006_working'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quotation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quotation_date', models.DateField()),
                ('client_name', models.CharField(max_length=500)),
                ('client_address1', models.CharField(max_length=500)),
                ('client_address2', models.CharField(max_length=500)),
                ('bill_or_quotation', models.CharField(choices=[('bill', 'BILL'), ('quotation', 'QUOTATION')], default='BILL', max_length=20)),
                ('materials', models.JSONField(default=list)),
                ('address_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='billing.companyaddress')),
                ('company_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='billing.company')),
                ('working_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='billing.working')),
            ],
        ),
    ]
