# Generated by Django 5.1.5 on 2025-01-28 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0008_quotation_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotation',
            name='total_amount',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='quotation',
            name='total_labour',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='quotation',
            name='total_materials',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
