# Generated by Django 5.1.5 on 2025-01-28 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0009_quotation_total_amount_quotation_total_labour_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotation',
            name='email_id',
            field=models.EmailField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='quotation',
            name='mobile_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
