# Generated by Django 5.1.5 on 2025-02-02 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0013_unit_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unit',
            name='name',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True),
        ),
    ]
